import Hero from "@/components/hero/Hero";
import { MyPosts, Posts } from "@/interface/postInterface";
import { getPosts } from "@/sanity/sanity-utils";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";

export default function Home({ posts }: MyPosts) {
  return (
    <>
      <Head>
        <title>TonniPaul Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />

        <div>
          {posts.map((post) => {
            return (
              <div key={post._createdAt}>
                <Image
                  src={post.image}
                  alt={post.slug}
                  width={700}
                  height={600}
                />
                {post.author}
              </div>
            );
          })}
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const posts: Posts[] = await getPosts();

  return {
    props: {
      posts,
    },
  };
}
